### ISSUE TITLE
image in a table

### ISSUE THREAD

**Issue by Adrjnk** [zsucic/captionmaker#2]
I work with tables where I put many images. 

![image](https://user-images.githubusercontent.com/61837593/195591874-a8ab452a-5231-4c0f-b118-251a1ac67521.png)

When I try use captionmaker It correctly founds images (number of images) but correct caption is being put only for images outside table. 

![image](https://user-images.githubusercontent.com/61837593/195591966-8f9dd19b-866d-49ee-813d-8bfb16e7c009.png)

![image](https://user-images.githubusercontent.com/61837593/195592008-f410243c-1a5f-4eb9-8c70-152ba3a65161.png)

**Comment by zsucic** [comment]
It's not an issue but rather a limitation of what CaptionMaker can do, if you refer to the manual here https://zsucic.com/captionmaker/

among other things, you'll find this:
"This brings us to first of few usage tips for Caption Maker:
TIP #1: Don't insert images, tables, drawings into other elements (e.g. in tables, headers, footers, etc.) if you want them to be recognized by Caption Maker and captioned accordingly. And, don't use "Inline" images and drawings because that is very similar to putting them into a table."

hopefully this explains it...
