### ISSUE TITLE
Service Documents failed while accessing document

### ISSUE THREAD

**Issue by davidbeglenboyle** [zsucic/captionmaker#5]
It appears to Captionize properly. I get the screen with a count of captions. But then I get:

"ScriptError: Service Documents failed while accessing document with id 10xt00YEjsiulWctUHoB4p_l-MPGzCyEi0SiTr0pN9ko."

(BTW THANKS for an awesome extension!)

**Comment by zsucic** [comment]
Hi, the error usualy means that you're using the add-on with a different account than the one you used to create the document. But I don't see how it would complete Captioning and then report this error... 
Could you check:
1. is the id reported the actual document id of the document you're trying to captionize? (you can check that by looking at the URL of the document when you open it, e.g. for:
https://docs.google.com/document/d/1NxS6R1rkxMf66qnfopOruocxKJWp5sL3Fvv7TEfg638/edit
the id would be: **1NxS6R1rkxMf66qnfopOruocxKJWp5sL3Fvv7TEfg638**
and
2. doublecheck if you've used the same account to create the document and to install the add-on. (usually people will have 1 private and 1 school or organization account and both are logged in within the same browser profile). If that's the case, I'd recommend setting up a separate browser profile for each of your accounts so that access privileges don't get confused. (see https://support.google.com/chrome/answer/2364824?hl=en&co=GENIE.Platform%3DDesktop )
3. if all above doesn't indicate anythign wrong, can you confirm if the problem occurs only on that one document or any document you try to captionize...

**Comment by davidbeglenboyle** [comment]
THANKS BTW. That fixed it. THANKS THANKS THANKS!!!

I used your tool to create https://prompt.mba/
