### ISSUE TITLE
Duplicates and triplicates

### ISSUE THREAD

**Issue by CivilEngPro** [zsucic/captionmaker#7]
Hello, I had this problem since yesterday.
In the document there are 378 images in total, and I configured the "Captionize!" button to show text like Figure {c}| {t}, in Times New Roman 10 with values 161 R 161 G 161 B in color, but then, everytime I press it, it stacks a lot of Figures, like this:
![image](https://user-images.githubusercontent.com/128521514/226706455-d8d417b2-0a38-4a2f-bb9e-4e50f9737d0c.png)

And I want to know how to resolve this because this is a really important document and I'm stressing myself
The values are (for images):
Old: {reg}^(Figure|Image)\s*([^a-z\s]*)\s*([^\n]*)$
New: Figura {c}| {t}
And for tables:
Old: {reg}^(Table)\s*([^a-z\s]*)\s*([^\n]*)$
New: Tabla {c}| {t}

And the "Auto update links" button is marked with a tick
Thanks in advance.
Also, it takes around 5 minutes to read every image, but that is no problem, I guess is due to the amount of images

**Comment by zsucic** [comment]
Hiya, based on your screenshot I'd say you can just change the 'old
caption' regex to say
Figura instead of Figure. The "old" regular expression is used to find any
previous captions and replace them rather than append.
You can learn more about regex here:
https://www.regular-expressions.info/quickstart.html
Regards,
Z

**Comment by zsucic** [comment]
And yeah, 380 images is a lot. The whole add-on is running on google docs
scripts infrastructure so there is no way for me to "speed it up". What's
even worse, you're fairly close to the maximum limit because google will
kill any function that runs for more than 6min. If that happens, your best
option is to split the document into 2 or more and work on each
individually. Then when you're fully happy with all parts you can copy
paste them back into 1...
If you do that, you can "offset" the enumeration for your 2nd and later
documents manually in the captionmaker settings...

**Comment by zsucic** [comment]
Hmm just noticed that you use | between the number and text, in which case
you might want to set it like this:

Old: {reg}^(Figura|Figure|Image)\|\s*([^a-z\s]*)\s*([^\n]


*)$New: Figura {c}| {t}And for tables:Old: {reg}^(Tabla|Table)\|\s*([^a-z\s]
*)\s*([^\n]*)$
New: Tabla {c}| {t}

I.e. put a \| after the brackets... (Just for clarity, that's "backslash"
followed by "pipe"

If that doesn't work, let me know and I'll figure out the correct regex for
you. Currently on my phone so can't really try it out, but i think it
should work.
Regards,
Z

**Comment by CivilEngPro** [comment]
You solved it in a milisecond. 
Also, the working time of the program was like 2:30 minutes, so I think that typing the "a" was easier for the program to read all the images
So, I'm glad and I really appreciate you solved it.
Thank you very much
